#!/bin/bash
ACTION="$@"
REPO_LIST=$(cat .github.repos)
for input in REPO_LIST; do
   input=${input//[$'\t\r\n']}
   COMMAND="git"
   LINE="$COMMAND $input"
   [ "$input" ] && eval "$LINE" && echo "$LINE"
done