#!/bin/bash
## CONFIG
ACTION="$@"
REPO_LIST=$(cat .github.repos)
USER=$(cat .github.user)
TOKEN=$(cat .github.token)
## COLORS
RED='\033[1;35m'
NC='\033[0m' # No Color
## START
for input in $REPO_LIST; do
   URL=${input//[$'\t\r\n']}
   BRANCH=${URL##*/}
   FOLDER_NAME=${BRANCH//.git}
   PROJECT_BRANCH=${URL##*/github.com/}
   URL_AUTH="https://$USER:$TOKEN@github.com/$PROJECT_BRANCH"
   ##LINE="git $ACTION"
   #echo "sh github.project $URL"
   #FOLDER_NAME=${"sh github.project $URL"}
   LINE="cd $FOLDER_NAME && git $ACTION && cd .."
   echo $ACTION
   [ $ACTION = "clone" ] && LINE="git clone $URL_AUTH"
   #echo -e "${RED}$LINE${NC}"
   [ "$input" ] && eval "$LINE"
done
